version: '3.3'

services:

  nginx:
    container_name: 'tvgrid-nginx'
    image: nginx
    ports:
      - "8080:80"
    links:
      - php-fpm
    env_file: .env
    volumes:
      - ./src:${APP_PATH_CONTAINER}
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  php-fpm:
    container_name: 'tvgrid-php-fpm'
    build: './src'
    volumes:
      - ./src:${APP_PATH_CONTAINER}
    ports:
      - "8000:80"
    depends_on: 
     - db
    user: 1000:1000
  
  db:
    image: mariadb
    container_name: 'tvgrid-db'
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=1
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./db/dump/tv.sql:/tv.sql
    ports:
      - "6800:3306"

  phpmyadmin:
    container_name: 'tvgrid-pma'
    image: phpmyadmin
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
    links:
      - db