version: '3.3'

services:

  nginx:
    container_name: 'tvgrid-nginx'
    image: nginx
    ports:
      - "8080:80"
    links:
      - php-fpm
    volumes:
    - ./src:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  php-fpm:
    container_name: 'tvgrid-php-fpm'
    build: './src'
    volumes:
      - ./src:/var/www/html
    ports:
      - 8000:80
    depends_on: 
     - db
  
  db:
    image: mariadb
    container_name: 'tvgrid-db'
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=1
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 6800:3306